### ISSUE TITLE
On MacOS had to manually create /Users/{$USER}/Library/Application Support/conductor/projects.json

### ISSUE THREAD

**Issue by richbradshaw** [mglaman/conductor#3]
Else program crashed.

**Comment by bojanz** [comment]
Same on Linux (/home/$myuser/.config/conductor/projects.json)

**Comment by mglaman** [comment]
Argh. Okay, on first open it writes the file - or should. I think the problem is that the folder isn't provisioned.

Should just be some initial "first boot" logic.
