### ISSUE TITLE
UX: Surprise popup caused me to start updating a requirement

### ISSUE THREAD

**Issue by daggerhart** [mglaman/conductor#38]
Hi,

I downloaded this project to see what it was all about. First thing I did was look around and saw a 2-column layout, clickables on the left and a frame on the right with details. I clicked on an item on the left expecting its details to appear on the right, but instead a new popup window appear with my mouse already on top of the "update" button which i immediately clicked by accident. 

Screenshots:

1. Click dependency
    ![conductor-ux-1](https://cloud.githubusercontent.com/assets/1205329/25569325/35b7f1c2-2de3-11e7-8b92-e46a974677a9.png)
2. Accidentally click update in surprise popup window
    ![conductor-ux-2](https://cloud.githubusercontent.com/assets/1205329/25569329/48b54432-2de3-11e7-8b3c-39cb9d6cd476.png)

Based on my immediate impression of the UI that was presented to me on the first run, I would expect that when I click on items in the left column, the details for that item appear in the right column.

Very excited to see where this ends up!

**Comment by mglaman** [comment]
@daggerhart so you're saying that clicking on items in sidebar should refresh main content, not open in a new popup for that package

**Comment by daggerhart** [comment]
Yes, I believe so. Generally speaking users have been trained that popups are bad.

The first problem is the surprise of something appearing in front of what you're looking at. I don't think you want to surprise users if at all possible. Surprises lead to mistakes. 

Also, windows for desktop apps get lost. They can end up behind other windows, or shrunken on their own in the dock/taskbar. This is needlessly confusing in most cases. When working with a many-windowed app, it is frustrating to keep navigating to a "Window" menu item to find what you're looking for.

About the current UX: Having the package window popout as a new window implies (to me) that the original window's content is still relevant and my place in that content should not be lost. But in this app I'm not sure if that is true. (I probably need to use it more to get a better idea of the value of the main window's right sidebar content) 

My feeling is that if I click on a package to get more information about that package, then that package's info is all I need to see for the moment. And if I want to go back to see information about the project as a whole, I can click on the project's name in the top left column.

This evening I will make some mockups to go along with this issue to help clarify what I'm picturing.

**Comment by daggerhart** [comment]
Here are some very simple mockups.

1. View the project window by clicking on composer.json
![conductor-project-mockup](https://cloud.githubusercontent.com/assets/1205329/25646905/ffde46a6-2f8a-11e7-8a71-c143867a58ae.jpg)

2. View a requirement/package by clicking on its name
![conductor-package-mockup](https://cloud.githubusercontent.com/assets/1205329/25646907/13fc3ea4-2f8b-11e7-897f-97db02f89be6.jpg)

**Comment by daggerhart** [comment]
This is resolved w/ PR: #46
