### ISSUE TITLE
Electron dependency is missing

### ISSUE THREAD

**Issue by jurgenhaas** [mglaman/conductor#8]
Great idea to build a UI for Composer. Like it.

When I tried, `npm start`faioled after `npm install` because of electron was missing. I moved it from the devDependencies to the dependencies section and then it worked.

**Comment by mglaman** [comment]
Ah, that's because I have it installed globally for other app development. That's a quick fix at least

**Comment by mglaman** [comment]
So I just ran `npm install` on a new machine and it all worked well. The `electron` dependency is a development dependency as it is not needed when a built binary is produced.

**Comment by jurgenhaas** [comment]
It's not working here. When I follow your instructions on the main page

```
git clone https://github.com/mglaman/conductor.git
cd conductor
npm install && npm start
```

I get the error that electron can not be found.
